### ISSUE TITLE
ZKLoginResult / client login:username password:pwd - exception crash - 10.12

### ISSUE THREAD

**Issue by johndpope** [superfell/SalesforceScripting#1]
I need to test the soap login for the zkSForce library as I'm getting an exception 

<img width="1648" alt="screen shot 2017-01-19 at 4 19 31 am" src="https://cloud.githubusercontent.com/assets/289994/22092741/423f49c4-de54-11e6-89be-d1462546abb3.png">

even though I'm wrapping this 
```

 @try {
        ZKLoginResult *result = [[SFDataEnvironment sharedSFDataEnvironment_instance].client login:username password:pwd];
        
    } @catch (ZKSoapException *e) {
        DLog(@"login failed %@", [e reason]);
}
```

It's worked for years - I jumped my own fork of the code - and for whatever reason - the client login / password is failing.
This is the only project I could uncover that actually uses the code base.
or is it? 

I've spent a couple of hours resurrecting this project to try and pin point if it's a problem with the library or my own fault.

Unfortunately - I wasn't able to get this app to login. urghhh......
The window doesn't popup ???
It's building though with pods - and I'm happy to fix other bugs / but I wonder if you could take a look
https://github.com/johndpope/SalesforceScripting

I'm going to abandon this - and test the SoqlX

**Comment by johndpope** [comment]
I added this code to the appdelegate and your code is working fine.
I'm using ARC - I don't know if Apple changed something under the hood in more recent OS. 
But on my ipad the code is blowing up.

 ZKSforceClient *client = [[ZKSforceClient alloc] init] ;
    @try {
        
        [client login:@"alistair.mcmaster@peters.com.au" password:@"password"];
        
    } @catch (ZKSoapException *ex) {
        NSLog(@"login failed %@", [ex reason]);
        // show to user etc, whatever you want to do when login fails.
    }

**Comment by superfell** [comment]
I don't know if this is your problem, but If you're building with a recent OSX SDK, you'll need to setup the ATS entries in your app's plist. see the section on Application Transport Security in the zkSforce readme https://github.com/superfell/zkSforce

**Comment by superfell** [comment]
There are also sample apps that call login in the zkSforce repo.

**Comment by johndpope** [comment]
I don't know - it's not related to ARC as I deleted all the files in this project - converted to ARC - and the client works fine. It just doesn't work in my project - I'm using the same podfile.

**Comment by johndpope** [comment]
hmmm.... only obvious difference is one is code running in ios10. 
the other is running fine on osx. 
I'll attempt to fire up a new ios project with a couple of lines to see if this will fail too.

**Comment by superfell** [comment]
Do you have Objective-C exceptions turned on in your project / build settings?

**Comment by johndpope** [comment]
ios10 is in the clear.
objective-c exceptions are turned on in both projects.
my new sample dummy project won't break/even with these on... 
so - I'll need to keep digging tomorrow. Thanks Simon
<img width="1628" alt="screen shot 2017-01-19 at 4 12 12 pm" src="https://cloud.githubusercontent.com/assets/289994/22094522/16ac3d36-de62-11e6-99e1-34e97e953a29.png">

**Comment by johndpope** [comment]
So I created a sample project to demonstrate crash
https://github.com/johndpope/crashSample
In the app delegate there's some code I'm using some from Salesforce /  @jhersh 
SFVAsync 
The problem is 
When I use a correct username + password the app runs fine.
When I don't - it's blowing up.

N.B. This sample app is NOT using ARC.
Tweaking the retains and releases to fix leaks - I think has caused something to go wrong. 
I will try to check out older commits to track down the commit.

I do appreciate all your efforts on this library and want to jump on the latest release - it's been years since I've fetched your code. I always had it in the back of my mind - that I'd jump on once the project was ARCi'fied. But you never did.  I don't know why. It's actually really helpful - and I've used retain / release back in the day.  
We could create an ARC branch - run tests - ask developers to help. 

Also I have these extensions zksForce
https://gist.github.com/johndpope/7ff31a98a2132734c05801f1c7888296

Using these classes (more so the logic) - it's possible to simplify the interaction with soap api particularly using custom objects. Which I imagine a lot of the use cases are for.

**Comment by superfell** [comment]
There's 2 problems and one is hiding the other. the operation block passed to performSFVAsyncRequest should return an NSObject *, but your's doesn't return anything, something i'd expect the compiler to spot, but also the declaration of the block is wrong, which is think is what's causing the compiler to not spot the problem.

If i change the perform call to this, it doesn't crash. (note the change to how the block parameter is declared, and the added return statement at the end.

      [SFVAsync performSFVAsyncRequest:^NSObject *{
            
            client = [[ZKSforceClient alloc] init] ;
            @try {
                
                // THIS WORKS
                // [client login:@"youremail@email.com" password:@"correctUsernameSecurityToken"];
                
                // This will CRASH!!
                [client login:@"youremail@email.com" password:@"incorrectUsernameSecurityToken"];
                
            } @catch (ZKSoapException *ex) {
                NSLog(@"login failed %@", [ex reason]);
                // show to user etc, whatever you want to do when login fails.
            }
            return nil;

**Comment by superfell** [comment]
For ARC,the project should cleanly convert to an ARC version with the wizard. There is an open issue to convert to ARC and modern objective-c syntax, but my projects that use this library are all ancient and don't use ARC, so its not a pressing need for me.

**Comment by superfell** [comment]
For your helpers whats the use case for those?, zkSforce works fine with custom objects, and create/update already supporting sending multiple objects.

**Comment by johndpope** [comment]
Thanks Simon, working great now. I owe you a beer. 
You might like this podcast with Chris Lattner talking about ARC / swift - http://atp.fm/episodes/205
With the custom objects - I'm using a meta model to describe my objects at runtime using meta model api -  this allows my code to be more dynamic. (like the native salesforce app)

Thanks again.
JP

**Comment by superfell** [comment]
Can you say more about how you can't do it with zkSforce directly? SoqlX for example is entirely generic, driven from the describeSObject() metadata

**Comment by johndpope** [comment]
Hi Simon,

fyi - for your reference - I found out that the armv64 if it's removed - it will cause this crash.  
<img width="827" alt="screen shot 2017-03-14 at 11 34 12 am" src="https://cloud.githubusercontent.com/assets/289994/23908367/32437b46-08aa-11e7-8095-22bafe03686c.png">

<img width="1655" alt="screen shot 2017-03-14 at 10 25 42 am" src="https://cloud.githubusercontent.com/assets/289994/23908215/c1306e50-08a9-11e7-9249-2f79d659178d.png">

ok - with regards to my helpers - it's all done at run time- there's no wsdl / files spat out.
I get that that's how some developers want to roll. 
Mine is a more a fluid approach / albeit the onus is on the developer to construct the xml correctly.

Authenticate / get session
// hit soap end point  to create object
// add appropriate headers 
<INJECT PAYLOAD HERE>
// end headers 

it's kind of wild west but I like it like this. 
I have other models which tie back to SQL lite and are not the stock models out of the box.

**Comment by johndpope** [comment]
Actually - there's a few more dials (xcode settings) that must be configured to force library to crash. 
https://github.com/johndpope/crashSample

Ahh - it's a frustrating crash - it's not consistently crashing now on my sample project / but is in my main code base. Leave this until I can consistently demonstrate error.

**Comment by johndpope** [comment]
I don't think it's the library - something's got corrupt with this project.
<img width="1550" alt="screen shot 2017-03-14 at 1 22 17 pm" src="https://cloud.githubusercontent.com/assets/289994/23913593/db666544-08b9-11e7-925e-d28ddd1546cc.png">

I resolved this by using physical device. Sighh.....
http://stackoverflow.com/questions/35939491/objective-c-not-catching-exception-in-try-catch-block/42794409#42794409
